# Generated by Django 4.2 on 2023-07-23 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sectors', '0006_alter_sectors_description_alter_sectors_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0006_alter_hospital_acronym'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=45, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOccupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, verbose_name='Code')),
                ('description', models.CharField(max_length=45, verbose_name='Descrição')),
                ('color_hex', models.CharField(max_length=7, verbose_name='color')),
            ],
        ),
        migrations.CreateModel(
            name='Beds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Nome')),
                ('type_occupation_description', models.TextField(max_length=255, verbose_name='Descrição tipo de ocupação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_extra', models.BooleanField(default=False, verbose_name='Extra')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital', verbose_name='Hospital')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sectors.sectors', verbose_name='Setor')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beds.type', verbose_name='Tipo')),
                ('type_occupation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beds.typeoccupation', verbose_name='Tipo de ocupação')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
            },
        ),
    ]
