# Generated by Django 4.2 on 2023-07-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0002_alter_type_options_alter_typeoccupation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Tipo de leito', 'verbose_name_plural': 'Tipo de leitos'},
        ),
        migrations.RemoveField(
            model_name='typeoccupation',
            name='color_hex',
        ),
        migrations.AlterField(
            model_name='typeoccupation',
            name='status',
            field=models.CharField(choices=[('BLOQUEADO', 'BLOQUEADO'), ('OCUPADO', 'OCUPADO'), ('VAGO', 'VAGO'), ('RESERVADO', 'RESERVADO')], max_length=45, verbose_name='status'),
        ),
    ]
