# Generated by Django 4.2 on 2023-07-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0004_remove_beds_hospital_alter_typeoccupation_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beds',
            options={'verbose_name': 'Leito', 'verbose_name_plural': 'Leitos'},
        ),
        migrations.RemoveField(
            model_name='beds',
            name='type_occupation_description',
        ),
        migrations.AlterField(
            model_name='typeoccupation',
            name='description',
            field=models.CharField(max_length=45, unique=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='typeoccupation',
            name='status',
            field=models.CharField(choices=[('OCUPADO', 'OCUPADO'), ('BLOQUEADO', 'BLOQUEADO'), ('VAGO', 'VAGO'), ('RESERVADO', 'RESERVADO')], max_length=45, verbose_name='status'),
        ),
    ]
