# Generated by Django 4.2 on 2023-07-29 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0005_alter_beds_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beds',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beds.type', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='typeoccupation',
            name='status',
            field=models.CharField(choices=[('VAGO', 'VAGO'), ('RESERVADO', 'RESERVADO'), ('OCUPADO', 'OCUPADO'), ('BLOQUEADO', 'BLOQUEADO')], max_length=45, verbose_name='status'),
        ),
    ]
