# Generated by Django 4.2 on 2023-06-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectors',
            name='activation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de ativação'),
        ),
        migrations.AlterField(
            model_name='sectors',
            name='deactivation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de desativação'),
        ),
    ]
