# Generated by Django 4.2 on 2023-06-17 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0002_alter_sectors_activation_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectors',
            options={'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
        migrations.AlterModelOptions(
            name='typeaccommodation',
            options={'verbose_name': 'Tipo de acomodação', 'verbose_name_plural': 'Tipos de acomodação'},
        ),
        migrations.AlterField(
            model_name='sectors',
            name='description',
            field=models.CharField(max_length=145, unique=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='sectors',
            name='resum',
            field=models.CharField(max_length=15, unique=True, verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='sectors',
            name='tip_acc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sectors.typeaccommodation', verbose_name='Tipo Acomodação'),
        ),
    ]
