# Generated by Django 4.2 on 2023-06-17 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0003_alter_sectors_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectors',
            name='tip_acc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sectors.typeaccommodation', verbose_name='Tipo Acomodação'),
        ),
    ]
