# Generated by Django 4.2 on 2023-06-07 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='cnes',
            field=models.IntegerField(default=1, unique=True, verbose_name='cnes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='cnpj',
            field=models.IntegerField(default=555, unique=True, verbose_name='cnpj'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospital',
            name='acronym',
            field=models.CharField(default='aaaa', max_length=45, unique=True, verbose_name='sigla'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospital',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='none'),
        ),
    ]
