# Generated by Django 4.2 on 2023-06-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_hospital_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='cnes',
            field=models.CharField(max_length=7, unique=True, verbose_name='cnes'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='nome'),
        ),
    ]
