# Generated by Django 4.2 on 2023-06-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_hospital_cnes_alter_hospital_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, verbose_name='cnpj'),
        ),
    ]
