# Generated by Django 4.2 on 2023-06-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_alter_hospital_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='acronym',
            field=models.CharField(max_length=10, unique=True, verbose_name='sigla'),
        ),
    ]
